### ISSUE TITLE
VMware appliance won't start

### ISSUE THREAD

**Issue by yuribernstein** [nextcloud/vm#43]
## Steps to reproduce
1. Download the VM appliance
2. Import it using VMware workstation player 12
3. Pass root credentials 

## Expected behaviour
Initial script should run

## Actual behaviour
Falls on "Testing if network is OK"
![nc_](https://cloud.githubusercontent.com/assets/22746335/19237052/63713224-8f03-11e6-8fde-a63bc61c39f6.PNG)

**Comment by enoch85** [comment]
@yuribernstein Thanks for reporting back to us! Can you please post the content of your interfaces file please?

**Comment by yuribernstein** [comment]
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback
# The primary network interface
auto ens33
ens34
iface ens33
ens34 inet dhcp
# This is an autoconfigured IPv6 interface
iface ens33
ens34 inet6 auto

**Comment by eplusk** [comment]
Your virtual machine has two interfaces !
The script is not configured to deal with this situation

nextcloud_install_production.sh:
IFACE=$(lshw -c network | grep "logical name" | awk '{print $3}')
better 
IFACE=$(lshw -c network | grep "logical name" | awk '{print $3; exit}')
if you only need the first interface

**Comment by enoch85** [comment]
Merged a commit that should fix this. Thanks for your suggestion @eplusk

**Comment by yuribernstein** [comment]
Great! thank you :)

**Comment by yuribernstein** [comment]
I re-download the community edition and imported it in vmplayer with 1 nic. still getting the same error
![interfaces](https://cloud.githubusercontent.com/assets/22746335/19518305/1b7d5eda-960f-11e6-875c-f60edcd295c1.PNG)

**Comment by yuribernstein** [comment]
![err](https://cloud.githubusercontent.com/assets/22746335/19518396/abd7738a-960f-11e6-9686-03d5d0e07104.PNG)

**Comment by yuribernstein** [comment]
btw, after uncommenting the whole section of check network in nexctcloud-startup-script.sh install process keeps running fine

**Comment by enoch85** [comment]
Which section did you uncomment?

**Comment by enoch85** [comment]
Can you run the script with debug turned on? Thanks!

**Comment by eplusk** [comment]
@yuribernstein  which mode has your net NAT or BRIGDED ?

**Comment by yuribernstein** [comment]
@enoch85  It seems that the script deletes itself after the installation, but it was the section in the beginning starting from "Testing if network is OK".
Could you please guide me how to turn on the debugging?
@eplusk I tried both and got the same result. Anyway when importing the appliance shouldn't it has the same settings as the original one?

**Comment by eplusk** [comment]
I remember, when I first installed the Appliance, i found an interface name which I didn't have.
I have to manually change the /etc/network/interfaces to use my real network interface name.
Perhaps the wrong name is in /etc/network/interfacec.d

**Comment by eplusk** [comment]
After testing a new virtual machine I found out:
In **/etc/network/interfaces** is the primary network interface  --> **ens33**
If I test the hardware with --> lshw -C network , I found  ->>  **logical name: enp0s3**
this name depends on the real machine you have.
Substituting **ens33** through **enp0s3** in /etc/network/interfaces makes a working network connection.

**Comment by enoch85** [comment]
This is fixed before anything else - here: https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L42-L46

You mean it diesn't work?

**Comment by enoch85** [comment]
Possible soulution, remove "source" from ip.sh

**Comment by eplusk** [comment]
@enoch85 the script nextcloud_install_production.sh gives an error in line 93, because a wget fails.
the script uses the network before you test it.

**Comment by eplusk** [comment]
@enoch85  Pardon, I was on the wrong steamboat  or as you say in german "Ich war auf dem falschen Dampfer".
after repairing the manually the wrong logical name, i tried to run the normal script ( nextcloud-startup-script.sh with  DEBUG=1, it runs without error.
now I test it with a "virgin" appliance

**Comment by eplusk** [comment]
the test with an new appliance started without network connection, but after running the startup script it has a working network connection and every thing was ok

**Comment by enoch85** [comment]
@eplusk Great news!
